export const Gents = {
    title: "Gents fashion",
    image1: "pics/boys/men1.avif",
    image2: "pics/boys/men2.avif",
    image3: "pics/boys/men3.avif",
    image4: "pics/boys/men4.avif",
    image5: "pics/boys/men5.avif",
    image6: "pics/boys/men7.avif",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR",
    price6:"959 INR",
}

export const Ladies = {
    title: "Ladies fashion",
    image1: "pics/girls/girl1.jpg",
    image2: "pics/girls/girl2.jpg",
    image3: "pics/girls/girl3.jpg",
    image4: "pics/girls/girl4.jpg",
    image5: "pics/girls/girl5.jpg",
    image6: "pics/girls/girl7.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR",
    price6:"959 INR",
}